# create a clean csv with 2010 population data
- state code 
- state 
- 2010 population 
# why 2010? 
- datasets for bigfoot and uap sightings include sightings from 1950 - 2010s
- uap reports are concentrated in the 2000 - 2010s
# create states table with bigfoot and ufo data

In [98]:
# Imports 

import pandas as pd

In [99]:
# Read original CSV 

states_df = pd.read_csv("data/US-population-by-state(wide).csv")

# Filter for 2010 and transpose
states_2010 = states_df[states_df['year'] == 2010].copy()

# Transpose so states become rows
states_2010_pop_df = states_2010.transpose().reset_index()

states_2010_pop_df.head(10)

                  index         121
0                  year      2010.0
1               Alabama   4785514.0
2                Alaska    710231.0
3               Arizona   6407342.0
4              Arkansas   2921998.0
5            California  37319550.0
6              Colorado   5047539.0
7           Connecticut   3579173.0
8              Delaware    899647.0
9  District of Columbia    605282.0

In [100]:
states_2010_pop_df.info

<bound method DataFrame.info of                    index         121
0                   year      2010.0
1                Alabama   4785514.0
2                 Alaska    710231.0
3                Arizona   6407342.0
4               Arkansas   2921998.0
5             California  37319550.0
6               Colorado   5047539.0
7            Connecticut   3579173.0
8               Delaware    899647.0
9   District of Columbia    605282.0
10               Florida  18846143.0
11               Georgia   9712209.0
12                Hawaii   1364004.0
13                 Idaho   1570819.0
14              Illinois  12840545.0
15               Indiana   6490555.0
16                  Iowa   3050819.0
17                Kansas   2858266.0
18              Kentucky   4348464.0
19             Louisiana   4544635.0
20                 Maine   1327651.0
21              Maryland   5788784.0
22         Massachusetts   6566440.0
23              Michigan   9877597.0
24             Minnesota   5310934.0
25           Mississippi   2970615.0
26              Missouri   5996089.0
27               Montana    990730.0
28              Nebraska   1829591.0
29                Nevada   2702483.0
30         New Hampshire   1316807.0
31            New Jersey   8799451.0
32            New Mexico   2064614.0
33              New York  19399956.0
34        North Carolina   9574586.0
35          North Dakota    674752.0
36                  Ohio  11539449.0
37              Oklahoma   3760014.0
38                Oregon   3837614.0
39          Pennsylvania  12711406.0
40          Rhode Island   1053994.0
41        South Carolina   4635846.0
42          South Dakota    816193.0
43             Tennessee   6355518.0
44                 Texas  25241897.0
45                  Utah   2775413.0
46               Vermont    625886.0
47              Virginia   8024004.0
48            Washington   6743009.0
49         West Virginia   1854265.0
50             Wisconsin   5690538.0
51               Wyoming    564531.0>

In [101]:
# Drop the unnecessary 'year' row that got transposed
states_2010_pop_df = states_2010_pop_df.drop(0).reset_index(drop=True)

# Rename columns 
states_2010_pop_df.columns = ['state', '2010_population']

In [102]:
# Drop any completely empty rows 
states_2010_pop_df = states_2010_pop_df.dropna(how='all')

In [103]:
# consider making this a function to reuse in notebooks

# Map state_code and use as id
state_to_code = {
    'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR',
    'California': 'CA', 'Colorado': 'CO', 'Connecticut': 'CT', 'Delaware': 'DE',
    'Florida': 'FL', 'Georgia': 'GA', 'Hawaii': 'HI', 'Idaho': 'ID',
    'Illinois': 'IL', 'Indiana': 'IN', 'Iowa': 'IA', 'Kansas': 'KS',
    'Kentucky': 'KY', 'Louisiana': 'LA', 'Maine': 'ME', 'Maryland': 'MD',
    'Massachusetts': 'MA', 'Michigan': 'MI', 'Minnesota': 'MN', 'Mississippi': 'MS',
    'Missouri': 'MO', 'Montana': 'MT', 'Nebraska': 'NE', 'Nevada': 'NV',
    'New Hampshire': 'NH', 'New Jersey': 'NJ', 'New Mexico': 'NM', 'New York': 'NY',
    'North Carolina': 'NC', 'North Dakota': 'ND', 'Ohio': 'OH', 'Oklahoma': 'OK',
    'Oregon': 'OR', 'Pennsylvania': 'PA', 'Rhode Island': 'RI', 'South Carolina': 'SC',
    'South Dakota': 'SD', 'Tennessee': 'TN', 'Texas': 'TX', 'Utah': 'UT',
    'Vermont': 'VT', 'Virginia': 'VA', 'Washington': 'WA', 'West Virginia': 'WV',
    'Wisconsin': 'WI', 'Wyoming': 'WY',
    'District of Columbia': 'DC'
}

states_2010_pop_df['state_code'] = states_2010_pop_df['state'].map(state_to_code)
states_2010_pop_df['state_code'] = states_2010_pop_df['state_code'].fillna('Unknown')

states_2010_pop_df.head()

        state  2010_population state_code
0     Alabama        4785514.0         AL
1      Alaska         710231.0         AK
2     Arizona        6407342.0         AZ
3    Arkansas        2921998.0         AR
4  California       37319550.0         CA

In [104]:
# Move state_code to first column - since it is the primary key
states_2010_pop_df.insert(0, 'state_code', states_2010_pop_df.pop('state_code'))

states_2010_pop_df.head()

  state_code       state  2010_population
0         AL     Alabama        4785514.0
1         AK      Alaska         710231.0
2         AZ     Arizona        6407342.0
3         AR    Arkansas        2921998.0
4         CA  California       37319550.0

In [105]:
# Order By State Code 

states_2010_pop_df = states_2010_pop_df.sort_values(by='state_code')

# Drop NA Values (currently 1 empty row at the end)
states_2010_pop_df.dropna()

# Check that all 50 States + DC are included 

states_2010_pop_df.head(51)

   state_code                 state  2010_population
1          AK                Alaska         710231.0
0          AL               Alabama        4785514.0
3          AR              Arkansas        2921998.0
2          AZ               Arizona        6407342.0
4          CA            California       37319550.0
5          CO              Colorado        5047539.0
6          CT           Connecticut        3579173.0
8          DC  District of Columbia         605282.0
7          DE              Delaware         899647.0
9          FL               Florida       18846143.0
10         GA               Georgia        9712209.0
11         HI                Hawaii        1364004.0
15         IA                  Iowa        3050819.0
12         ID                 Idaho        1570819.0
13         IL              Illinois       12840545.0
14         IN               Indiana        6490555.0
16         KS                Kansas        2858266.0
17         KY              Kentucky        4348464.0
18         LA             Louisiana        4544635.0
21         MA         Massachusetts        6566440.0
20         MD              Maryland        5788784.0
19         ME                 Maine        1327651.0
22         MI              Michigan        9877597.0
23         MN             Minnesota        5310934.0
25         MO              Missouri        5996089.0
24         MS           Mississippi        2970615.0
26         MT               Montana         990730.0
33         NC        North Carolina        9574586.0
34         ND          North Dakota         674752.0
27         NE              Nebraska        1829591.0
29         NH         New Hampshire        1316807.0
30         NJ            New Jersey        8799451.0
31         NM            New Mexico        2064614.0
28         NV                Nevada        2702483.0
32         NY              New York       19399956.0
35         OH                  Ohio       11539449.0
36         OK              Oklahoma        3760014.0
37         OR                Oregon        3837614.0
38         PA          Pennsylvania       12711406.0
39         RI          Rhode Island        1053994.0
40         SC        South Carolina        4635846.0
41         SD          South Dakota         816193.0
42         TN             Tennessee        6355518.0
43         TX                 Texas       25241897.0
44         UT                  Utah        2775413.0
46         VA              Virginia        8024004.0
45         VT               Vermont         625886.0
47         WA            Washington        6743009.0
49         WI             Wisconsin        5690538.0
48         WV         West Virginia        1854265.0
50         WY               Wyoming         564531.0

# write to csv

In [106]:
states_2010_pop_df.to_csv("data/states_2010_population_data.csv", index=False)

# Note: Fix issue with extra empty row at the end of the csv